# Generated by Django 2.2.4 on 2020-12-30 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_info', '0002_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_size_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_info.pizza_size'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_toppings_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_info.pizza_toppings'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_info.pizza_type'),
        ),
    ]
