# Generated by Django 2.2.4 on 2020-12-30 11:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_info', '0003_auto_20201230_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='toppings',
            fields=[
                ('toppings_id', models.AutoField(primary_key=True, serialize=False)),
                ('toppings', models.CharField(blank=True, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_info.pizza_status')),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_toppings_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_info.toppings'),
        ),
        migrations.DeleteModel(
            name='pizza_toppings',
        ),
    ]
