# Generated by Django 2.2.4 on 2020-12-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_info', '0004_auto_20201230_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='pizza_toppings_id',
            new_name='toppings_id',
        ),
    ]
